POINTING_DEVICE_DRIVER = analog_joystick
SRC += lib/oled.c
VIA_ENABLE=yes
# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = custom
# OPT_DEFS += -DTHUMBSTICK_ENABLE
# AUDIO_ENABLE = no

